### ISSUE TITLE
TVING 실시간은 정기결제 이용권만 가능한건가요?

### ISSUE THREAD

**Issue by hoonsoft** [HISONA/allive#1]
무제한플러스(뷰잉 6개월) 180일권을 이용중입니다.
tving에서 드라마나 예능 등 정주행채널은 잘나옵니다만 실시간채널은 '이용권을 구매 후 시청할 수 있습니다'라고만 뜨고 전부 재생이 안되네요 ㅜ 정기결제 이용자만 tving실시간채널 이용이 가능한건가요?

**Comment by HISONA** [comment]
테스트 해보니 특정 계정이 로그인은 되었으나 재생정보를 요청할때 로그인이 안된 것 처럼 서버에서 응답을 주는 경우가 있는 것 같습니다. 
로그인을 보강하기는 했는데 정확한 해결책인지는 좀 더 테스트가 필요할 것 같습니다. 

계속 안되실 경우에는 https://www.tving.com 에서 로그인을 수행한 후에 앱에서 다시 로그인을 해보시기 바랍니다.

**Comment by hoonsoft** [comment]
고맙습니다! 바로 설치해봤는데 잘 되네요!
