### ISSUE TITLE
티빙에서 프로필 선택이 안됩니다.

### ISSUE THREAD

**Issue by tikle00** [HISONA/allive#21]
12월 15일 업그레이드된 요금정책으로 4명까지 프로필 생성이 가능한데,
현제 Allive TV에서 로그인 정보 입력해도 프로필 선택창이 안나오네요.
참고로 웨이브는 나옵니다.

**Comment by HISONA** [comment]
동시 시청이 프로필 단위가 아니라 계정 단위로 제한이 되고 있고, 라이브 채널은 프로필에 시청 기록에 남지 않아서 프로필 선택이 의미가 없습니다. 
계정 로그인만 하셔도 상관 없습니다.

**Comment by tikle00** [comment]
확인 감사합니다
