### ISSUE TITLE
길게누름 인식을 더 길게 해주세요

### ISSUE THREAD

**Issue by rootkgh** [HISONA/allive#26]
리모컨 버튼이 0.5초 정도 눌러지는 형태인데
(누르고 있르면 연속인식이 그정도..)
최근 업데이트루 길게로만 인식이 됩니다

기존보다 길게 누르기 시간이 준 것 같습니다
다시 좀 더 길게 해주세요

**Comment by HISONA** [comment]
LongPress 버튼이 안드로이드 시스템에서 보내주는 이벤트라 시간 조절을 따로 할수가 없습니다.
이전 버전에는 LongPress 기능이 없었는데, 3.1 버전에 LongPress 기능으로 마이채널 선택/해제 기능이 들어가 있어서 
그렇게 느끼셨을 것 같네요. 
플레이어에서도 마이채널 선택을 할 수 있기 때문에, 다음 버전에 마이채널 선택을 ON/OFF 할 수 있는 기능을 추가하면 될 것 같네요.

**Comment by rootkgh** [comment]
잘사용하고 있습니다
감사합니다

리모컨이 longpress로되는 문제로 이해되는데, 별도 on/off가 생기니 편하네요
