### ISSUE TITLE
지원 대상을 추가하실 계획이 있으신가요?

### ISSUE THREAD

**Issue by keicoon** [HISONA/allive#36]
안녕하세요. 본 프로그램을 매우 잘 이용하고 있어 제공해주신 기능에 감사드립니다.
해당 앱만 가지고 올인원처럼 다른 스트리밍 서비스도 사용하고 싶은데 **트위치**를 지원해주실 생각 있으신가요?

가능하다면 트위치 모듈쪽 작업에 도움을 드려서라도 사용하고 싶은 마음에 이슈로 남기고 갑니다.

항상 감사합니다!

**Comment by HISONA** [comment]
현재 WAVVE 나 TVING 으로부터 정식으로 허용된 앱이 아니라서 확장하는데 문제가 있을 것 같습니다. 
(WAVVE 나 TVING 으로 부터 제재가 있을 수 있습니다.)
별도 앱으로 개발을 하시는 것이 나을 것 같습니다.
