### ISSUE TITLE
갤럭시 노트 10 + 사용자 입니다.

### ISSUE THREAD

**Issue by ccsjb12** [HISONA/allive#43]
3.4까지는 설치되는데 3.5부터 "앱이 설치되지 않았습니다."라고 나옵니다. 기존 앱 삭제해봐도 마찬가지이고 알수없는 출처 설치허용 래놨는데도 안되네요.

**Comment by HISONA** [comment]
signing 이슈인 것으로 보이는데요. 
하위호환을 위해서 v1 으로 signing 되어 있는데, 아래 버전을 설치해 보세요. 
 
https://github.com/HISONA/allive/releases/download/v3.7/allive-v3.7-v2-release.apk

**Comment by ccsjb12** [comment]
> signing 이슈인 것으로 보이는데요.
> 하위호환을 위해서 v1 으로 signing 되어 있는데, 아래 버전을 설치해 보세요.
> 
> https://github.com/HISONA/allive/releases/download/v3.7/allive-v3.7-v2-release.apk

**Comment by ccsjb12** [comment]
설치됩니다. 감사합니다.
