### ISSUE TITLE
(해결완료) 4.0에서도 웨이브 실시간 재생불가 문의

### ISSUE THREAD

**Issue by Jonny806** [HISONA/allive#89]
안녕하세요
안드로이드TV (이스트라 쿠카75) 사용자입니다
항상 Allive 앱 유용하게 감사히 잘 써오고 있었습니다.

현재 웨이브 유료 최상등급 계정을 4명 1계정 공유로 쓰고있었구요
3.8 3.9에서도 동일했지만 4.0 에서도 여전히 실시간 재생이 안돼 문의드립니다.

앱 캐시&데이터 삭제 -> 앱 완전삭제 -> 3.8 3.9 4.0 apk 다운&설치 
-> 웨이브 계정로그인 -> 실시간 채널들 선택 시 어떠한 채널도 재생불가 바로 홈화면으로 튕김
(재생희망 채널을 꾹 눌러서 마이채널 등록 후 마이채널란에서 재생시도 시 동일하게 홈화면으로 튕김)

혹시 공유계정 접속자수 초과라 안되는가 싶어서 TV에서 홈화면으로 튕길 시
폰에서 동일채널 접속 시 실시간재생잘되서 동시접속문제는 아닌것 같구요

TV에 웨이브 공식APP 최신버전 설치 및 로그인까지는 완료돼있고
거기에 웨이브 4.0 설치 후 현재와같은 상황입니다

혹시 저처럼 웨이브만 쓰는데, 3.8~4.0까지 계속해서 모든채널
재생시도 시 홈화면으로 바로 튕겨버리시는 분들 안계실까요??

**Comment by BLOODTYP** [comment]
전 이스트라 쿠카 셋톱 박스 이용중인데 무료계정으로 10분후 멈추지만 앱튕김 증상은 없네요

**Comment by AntiBigmac** [comment]
한번 TV 초기화를 해 보세요. 3.8에서는 웨이브 에서 문제가 있다면요.

**Comment by Jonny806** [comment]
안녕하세요. 오늘아침 최종테스트 후 안되면 TV자체 초기화하려했는데 현재 4.0버전으로 마이채널 등록안해도 전채널 재생잘됩니다. 

글 등록 전 후 했던건..TV 재부팅 3~4차례..? 밖에 없었던것 같아요. 제 생각이지만 본문의 저같은 상황엔 TV전체를 3~4차례 재부팅 해보고 TV를 좀 오래 꺼뒀다가 켜보고 테스트 해보시길 권해드립니다.

상기 조언 주신분들께 다시한번 감사드립니다. ^^
